<%@ page language="java" contentType="text/html;charset=utf-8" pageEncoding="utf-8"%>
<html>    <meta http-equiv='Content-Type' content='text/html;charset=utf-8'/>    <head>	<style>	 a:link {	     color:#175199; }	 a:visited {	     color:#1a1a1a;	 }	 a:hover {	     color: #175199;	 }	 a:active {	     color:#4285f4;	 }	 a{	     text-decoration:none;	     font-size:109%;	 }	 html,body{	     background-color:#ffffff;	     width:99%;	     height:98%;	     overflow-x:hidden;	 }	 ::-webkit-scrollbar{	     width:6px;	     border-radius:8px;	     background-color:#FBBC05;	 }	 ::-webkit-scrollbar-track{    border-radius:8px;	 }	 ::-webkit-scrollbar-thumb{	     border-radius:8px;	     -webkit-box-shadow:inset 0 0 3px rgba(0,0,0,.3);	     background-color:#EA4335;	 }	 img.title{	     display:none;	 }	</style><body>	<form action='/prj/wobbs/ReplyServlet' method='post' name='commonForm' id='commonForm' target='parent.window.auxiliary'>	    <input type='hidden' name='like' id='like' value='0'>	    <input type='hidden' name='diss' id='diss' value='0'>	    <input type='hidden' name='report' id='report' value='0'>	    <input type='hidden' name='share' id='share' value='0'>	    <input type='hidden' name='favorite' id='favorite' value='0'>	    <input type='hidden' name='POSTID' id='POSTID' value="+postId+">	    <input type='hidden' name='replyId' id='replyId' value='0'>	    <input type='hidden' name='type' id='type' value='0'>	    <input type='hidden'  name='comment' id='comment' value >	</form>
    <body >

	    <div style='white-space:nowrap;'>
		<a href='javascript:' onclick='clickImg("++")'> <img id="++" src="+new FindUserAvatar().Find()+" style='width:50px;border-radius:3px;'></img> </a><a href='javascript:' onclick='clickUser("++") id="++"> <span style='color:#444444;'>  "+ +"</span> </a> <span style='float:right;font-size:90%;padding-right:9px;'><img title=''热度' src='/prj/wobbs/img/hot.gif'>"++" <a href='javascript:' id="++" onclick='clickShare("++")' style='margin-left:10px;color:#76839b;font-size:92%;'>分享</a>		<a href='javascript:' onclick='clickFavorite("++")' style='margin-left:10px;color:#76839b;font-size:92%;'>收藏</a> </span> </div> <div> <h4> "+  +"</h4><br> </div> <div> <p> "++"</p></div> <div style='white-space:nowrap;'><a id='postLike"++"' href='javascript:' onclick='clickLike("++");' style='font-size:200%;color:#d9edff;' title='我觉得OK'>▲</a> <a id='postDiss"+mixPara[0]+"' style='font-size:200%;color:#d9edff;' href='javascript:' onclick='clickDiss(\"postDiss"+mixPara[0]+"\")' title='我觉得不行'>▼</a> <a href='javascript:' onclick='clickReply(\"postReply"+mixPara[0]+"\");' style='margin-left:10px;color:#76839b;font-size:92%;'>评论("+ mixPara[6] +")</a>	<div id='postReply"+mixPara[0]+"' style='display:none' name='postReply"+mixPara[0]+"'>  <textarea rows='6' style=\"width:70%;margin-left:83px;\" name=\"postContents"+mixPara[0]+"\" id='postContents"+mixPara[0]+"'></textarea><button  id=\"postPublish"+mixPara[0]+"\" style=\"border-radius:5px;border:0px;background-color:;\" onclick='clickPublish(\"postContents"+mixPara[0]+",postReply"+mixPara[0]+",post"+mixPara[0]+"\")'>发布</button>  </div>	<a href='javascript:' onclick='clickReport(\"postReport"+mixPara[0]+"\")' style='margin-right:3px;font-size:60%;float:right;'>举报</a> <span style='font-size:80%;float:right;'>"+mixPara[5].substring(0,mixPara[5].length()-2)+" </span>  </div><img src='/prj/wobbs/img/postsTitleSplit.png' style='width:1000px;' >
	</div>
    </body>
</html>
