<%@ page language="java" contentType="text/html;charset=utf-8" pageEncoding="utf-8"%>
<html>
    <head>
	<script>	 	 function getScrollTop(){	     var scrollTop=0,bodyScrollTop=0,documentScrollTop=0;	    if(document.body){	    bodyScrollTop=document.body.scrollTop;	    }	    if(document.documentElement){	    documentScrollTop=document.documentElement.scrollTop;	    }	     scrollTop=(bodyScrollTop-documentScrollTop>0)?bodyScrollTop:documentScrollTop;	     	     	    return scrollTop;	    }	    function getScrollHeight(){	    var scrollHeight=0,bodyScrollHeight=0,documentScrollHeight=0;	    if(document.body){	    bodyScrollHeight=document.body.scrollHeight;	    }if(document.documentElement){	    documentScrollHeight=document.documentElement.scrollHeight;	    }	    scrollHeight=(bodyScrollHeight-documentScrollHeight>0)?bodyScrollHeight:documentScrollHeight;	    return scrollHeight;	    }	    function getWindowHeight(){	    var windowHeight=0;	    if(document.compatMode==\"CSS1Compat\"){	    windowHeight=document.documentElement.clientHeight;	    }	    else{	    windowHeight=document.body.clientHeight;	    }	    return windowHeight;	    }	    window.onscroll=function(){	    if(getScrollTop()+getWindowHeight()>getScrollHeight()==1/2){    alert(getScrollTop()); }	    }</script>	 </head> <body onload='alert(getScrollTop()+getWindowHeight()+\"::\"+getScrollHeight())'>
	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasfflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>	    <p>dsfakljasflkasjf<br></p>
	<form action='' id='' method=''>
	    <input type='text' name='addPosts' id='addPosts' style='display:none'>
	    <input type='submit' name='submit' id='submit' style='display:none'>
	</form>
	fdsaflksldajflksdf
	<a id='prevPage' href='javascript:' onclick='' style='visibility:hidden'>上一页</a>
	<a id='nextPage' href='javascript:' onclick='' style='visibility:hidden'>下一页</a>
    </body>
</html>
